"""
Gyrocompass overhaul checklist categories organized by model
"""

# Different gyrocompass models with their specific checklists
GYRO_MODELS = {
    "Yogkowaga CMZ700": {
        "manufacturer": "Yogkowaga",
        "type": "Electronic Gyrocompass",
        "description": "Yogkowaga CMZ700 Marine Gyrocompass"
    },
    "Yogkowaga CMZ900": {
        "manufacturer": "Yogkowaga",
        "type": "Electronic Gyrocompass",
        "description": "Yogkowaga CMZ900 Marine Gyrocompass"
    },
    "Anschütz STD22": {
        "manufacturer": "Anschütz",
        "type": "Electronic Gyrocompass",
        "description": "Anschütz STD22 Standard Gyrocompass"
    },
    "Simrad GC80/85": {
        "manufacturer": "Simrad",
        "type": "Electronic Gyrocompass",
        "description": "Simrad GC80/85 Integrated Gyrocompass"
    }
}

# Model-specific checklist categories
CHECKLIST_CATEGORIES = {
    "Yogkowaga CMZ700": {
        "Initial Inspection": [
            "Visual inspection of external casing",
            "Check for physical damage or corrosion",
            "Verify mounting hardware integrity",
            "Inspect electrical connectors",
            "Document current condition with photos",
            "Check serial number and model number",
            "Verify equipment documentation available",
        ],
        "Mechanical Inspection": [
            "Remove protective covers",
            "Inspect rotor assembly",
            "Check gyroscope bearings for wear",
            "Verify gimbal suspension integrity",
            "Inspect follow-up system",
            "Check erection mechanism",
            "Verify damping system components",
            "Lubricate bearings if required",
        ],
        "Electrical Testing": [
            "Test power supply voltage",
            "Measure current draw",
            "Check heating element resistance",
            "Verify synchronous motor function",
            "Test servo motor operation",
            "Check amplifier circuits",
            "Verify signal conditioning circuits",
            "Test compass repeater connections",
        ],
        "Functional Testing": [
            "Spin up gyroscope (no load)",
            "Monitor spin-up time",
            "Check for vibration or noise",
            "Verify precession movement",
            "Test settling time after disturbance",
            "Verify heading lock function",
            "Test rate of turn response",
            "Check heading repeatability",
        ],
        "Alignment & Calibration": [
            "Perform gyro leveling",
            "Check meridian transit accuracy",
            "Calibrate compass azimuth",
            "Verify latitude correction settings",
            "Test course-up repeater synchronization",
            "Perform earth rate compensation check",
            "Calibrate heading output",
        ],
        "System Integration & Testing": [
            "Test NMEA 0183 output",
            "Verify autopilot integration",
            "Test chart plotter interface",
            "Verify backup power operation",
            "Test alarm/warning systems",
            "Document all test readings",
        ],
        "Documentation & Cleanup": [
            "Document all test results",
            "Record any replacements made",
            "Note lubrication points serviced",
            "Clean exterior surfaces",
            "Reinstall protective covers",
            "Verify all connections are secure",
            "Update maintenance log",
            "Complete maintenance record",
        ],
    },
    "Yogkowaga CMZ900": {
        "Initial Inspection": [
            "Visual inspection of external casing",
            "Check for physical damage or corrosion",
            "Verify mounting hardware integrity",
            "Inspect electrical connectors",
            "Document current condition with photos",
            "Check serial number and model number",
            "Verify equipment documentation available",
            "Inspect redundancy system indicators",
        ],
        "Mechanical Inspection": [
            "Remove protective covers",
            "Inspect rotor assembly",
            "Check gyroscope bearings for wear",
            "Verify gimbal suspension integrity",
            "Inspect follow-up system",
            "Check erection mechanism",
            "Verify damping system components",
            "Lubricate bearings if required",
            "Inspect dual-channel components",
        ],
        "Electrical Testing": [
            "Test primary power supply voltage",
            "Test secondary power supply voltage",
            "Measure current draw on both channels",
            "Check heating element resistance",
            "Verify synchronous motor function",
            "Test servo motor operation",
            "Check amplifier circuits (both channels)",
            "Verify signal conditioning circuits",
            "Test compass repeater connections",
            "Test cross-track monitoring system",
        ],
        "Functional Testing": [
            "Spin up gyroscope (primary channel)",
            "Spin up gyroscope (secondary channel)",
            "Monitor spin-up time for both channels",
            "Check for vibration or noise",
            "Verify precession movement",
            "Test settling time after disturbance",
            "Verify heading lock function",
            "Test rate of turn response",
            "Check heading repeatability",
            "Test redundancy switching",
            "Verify cross-track output accuracy",
        ],
        "Alignment & Calibration": [
            "Perform gyro leveling (primary)",
            "Perform gyro leveling (secondary)",
            "Check meridian transit accuracy",
            "Calibrate compass azimuth (primary)",
            "Calibrate compass azimuth (secondary)",
            "Verify latitude correction settings",
            "Test course-up repeater synchronization",
            "Perform earth rate compensation check",
            "Verify dual-channel alignment",
        ],
        "System Integration & Testing": [
            "Test NMEA 0183 output (primary)",
            "Test NMEA 0183 output (secondary)",
            "Verify autopilot integration",
            "Test chart plotter interface",
            "Test redundancy alarm system",
            "Verify channel switching logic",
            "Test backup power operation",
            "Document all test readings",
        ],
        "Documentation & Cleanup": [
            "Document all test results (both channels)",
            "Record any replacements made",
            "Note lubrication points serviced",
            "Clean exterior surfaces",
            "Reinstall protective covers",
            "Verify all connections are secure",
            "Update maintenance log",
            "Complete maintenance record with redundancy notes",
        ],
    },
    "Anschütz STD22": {
        "Initial Inspection": [
            "Visual inspection of external casing",
            "Check for physical damage or corrosion",
            "Verify mounting hardware integrity",
            "Inspect electrical connectors",
            "Document current condition with photos",
            "Check serial number and model number",
            "Verify equipment documentation available",
            "Check resolver coupling alignment",
        ],
        "Mechanical Inspection": [
            "Remove protective covers (compact design access)",
            "Inspect rotor assembly",
            "Check gyroscope bearings for wear",
            "Verify gimbal suspension integrity",
            "Inspect follow-up system",
            "Check erection mechanism",
            "Verify damping system components",
            "Lubricate bearings if required",
            "Inspect resolver mechanism",
        ],
        "Electrical Testing": [
            "Test power supply voltage",
            "Measure current draw",
            "Check heating element resistance",
            "Verify synchronous motor function",
            "Test servo motor operation",
            "Check resolver output signal quality",
            "Verify amplifier circuits",
            "Test signal conditioning circuits",
            "Test compass repeater connections",
            "Check synchro/resolver output accuracy",
        ],
        "Functional Testing": [
            "Spin up gyroscope (no load)",
            "Monitor spin-up time",
            "Check for vibration or noise",
            "Verify precession movement",
            "Test settling time after disturbance",
            "Verify heading lock function",
            "Test rate of turn response",
            "Check heading repeatability",
            "Verify resolver alignment precision",
        ],
        "Alignment & Calibration": [
            "Perform gyro leveling",
            "Check meridian transit accuracy",
            "Calibrate compass azimuth",
            "Verify resolver alignment precision",
            "Verify latitude correction settings",
            "Test course-up repeater synchronization",
            "Perform earth rate compensation check",
            "Calibrate heading output",
            "Verify resolver zero point",
        ],
        "System Integration & Testing": [
            "Test NMEA 0183 output",
            "Verify autopilot integration",
            "Test chart plotter interface",
            "Verify resolver signal to navigation system",
            "Test backup power operation",
            "Test alarm/warning systems",
            "Document all test readings",
        ],
        "Documentation & Cleanup": [
            "Document all test results",
            "Record any replacements made",
            "Note resolver alignment adjustments",
            "Note lubrication points serviced",
            "Clean exterior surfaces",
            "Reinstall protective covers",
            "Verify all connections are secure",
            "Update maintenance log",
            "Complete maintenance record",
        ],
    },
    "Simrad GC80/85": {
        "Initial Inspection": [
            "Visual inspection of external casing",
            "Check for physical damage or corrosion",
            "Verify mounting hardware integrity",
            "Inspect electrical connectors",
            "Document current condition with photos",
            "Check serial number and model number",
            "Verify equipment documentation available",
            "Check network connections and IP configuration",
        ],
        "Mechanical Inspection": [
            "Remove protective covers",
            "Inspect rotor assembly",
            "Check gyroscope bearings for wear",
            "Verify gimbal suspension integrity",
            "Inspect follow-up system",
            "Check erection mechanism",
            "Verify damping system components",
            "Lubricate bearings if required",
        ],
        "Electrical Testing": [
            "Test power supply voltage",
            "Measure current draw",
            "Check heating element resistance",
            "Verify synchronous motor function",
            "Test servo motor operation",
            "Check amplifier circuits",
            "Verify signal conditioning circuits",
            "Test Ethernet network connectivity",
            "Verify network communication",
        ],
        "Functional Testing": [
            "Spin up gyroscope (no load)",
            "Monitor spin-up time",
            "Check for vibration or noise",
            "Verify precession movement",
            "Test settling time after disturbance",
            "Verify heading lock function",
            "Test rate of turn response",
            "Check heading repeatability",
            "Test ECDIS integration functionality",
        ],
        "Alignment & Calibration": [
            "Perform gyro leveling",
            "Check meridian transit accuracy",
            "Calibrate compass azimuth",
            "Verify latitude correction settings",
            "Test course-up repeater synchronization",
            "Perform earth rate compensation check",
            "Calibrate heading output",
            "Verify ECDIS heading synchronization",
        ],
        "System Integration & Testing": [
            "Test NMEA 0183 output",
            "Test network data transmission",
            "Verify autopilot integration (CAN/Ethernet)",
            "Test ECDIS interface and display",
            "Test chart plotter interface",
            "Verify integrated navigation system",
            "Test backup power operation",
            "Test alarm/warning systems",
            "Verify integrated display functionality",
            "Document all test readings",
        ],
        "Documentation & Cleanup": [
            "Document all test results",
            "Record any replacements made",
            "Note network configuration details",
            "Note lubrication points serviced",
            "Clean exterior surfaces",
            "Reinstall protective covers",
            "Verify all connections are secure",
            "Update maintenance log",
            "Complete maintenance record with integration notes",
        ],
    }
}

# Standard test acceptance criteria
TEST_CRITERIA = {
    "Spin-up Time": "Should complete within 3-5 minutes",
    "Settling Time": "Should stabilize within 15 minutes",
    "Heading Accuracy": "±1° or better",
    "Repeatability": "Within 0.5° over 24 hours",
    "Response Time": "Less than 10 seconds to course change",
    "Gyro Error": "Less than ±2° per hour",
}

# Model-specific notes
MODEL_NOTES = {
    "Yogkowaga CMZ700": "Entry-level electronic compass - Check heating elements and servo calibration carefully. Standard NMEA integration.",
    "Yogkowaga CMZ900": "Advanced electronic compass with dual-channel redundancy - Verify both channels independently. Test cross-track monitoring output.",
    "Anschütz STD22": "Compact design with limited internal access - Check resolver alignment precision carefully. Pay attention to mechanical linkages.",
    "Simrad GC80/85": "Modern integrated ECDIS system - Network integration critical. Test Ethernet connectivity and ECDIS display synchronization.",
}
